language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
script:
  - pushd examples/esp8285_rainbow && cp credentials.sample.h credentials.h && pio run && popd
  - pushd examples/uno_rainbow && pio run && popd
